// Generated by rstantools.  Do not edit by hand.

/*
    fluxr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    fluxr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with fluxr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_o2_twostation_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'o2_twostation', line 41, column 2 to column 45)",
                                                      " (in 'o2_twostation', line 42, column 2 to column 43)",
                                                      " (in 'o2_twostation', line 43, column 2 to column 32)",
                                                      " (in 'o2_twostation', line 44, column 2 to column 41)",
                                                      " (in 'o2_twostation', line 48, column 2 to column 34)",
                                                      " (in 'o2_twostation', line 51, column 2 to column 24)",
                                                      " (in 'o2_twostation', line 52, column 2 to column 23)",
                                                      " (in 'o2_twostation', line 53, column 2 to column 24)",
                                                      " (in 'o2_twostation', line 54, column 2 to column 27)",
                                                      " (in 'o2_twostation', line 56, column 2 to column 73)",
                                                      " (in 'o2_twostation', line 66, column 4 to column 49)",
                                                      " (in 'o2_twostation', line 67, column 4 to column 46)",
                                                      " (in 'o2_twostation', line 68, column 4 to column 44)",
                                                      " (in 'o2_twostation', line 65, column 17 to line 69, column 3)",
                                                      " (in 'o2_twostation', line 65, column 2 to line 69, column 3)",
                                                      " (in 'o2_twostation', line 76, column 4 to line 83, column 35)",
                                                      " (in 'o2_twostation', line 73, column 15 to line 84, column 3)",
                                                      " (in 'o2_twostation', line 73, column 2 to line 84, column 3)",
                                                      " (in 'o2_twostation', line 99, column 2 to column 27)",
                                                      " (in 'o2_twostation', line 100, column 2 to column 16)",
                                                      " (in 'o2_twostation', line 101, column 2 to column 15)",
                                                      " (in 'o2_twostation', line 102, column 2 to column 28)",
                                                      " (in 'o2_twostation', line 103, column 2 to column 28)",
                                                      " (in 'o2_twostation', line 104, column 2 to column 18)",
                                                      " (in 'o2_twostation', line 106, column 4 to column 53)",
                                                      " (in 'o2_twostation', line 105, column 15 to line 107, column 3)",
                                                      " (in 'o2_twostation', line 105, column 2 to line 107, column 3)",
                                                      " (in 'o2_twostation', line 109, column 4 to column 42)",
                                                      " (in 'o2_twostation', line 110, column 4 to column 40)",
                                                      " (in 'o2_twostation', line 113, column 6 to column 44)",
                                                      " (in 'o2_twostation', line 114, column 6 to column 44)",
                                                      " (in 'o2_twostation', line 112, column 17 to line 115, column 5)",
                                                      " (in 'o2_twostation', line 112, column 4 to line 115, column 5)",
                                                      " (in 'o2_twostation', line 116, column 4 to column 193)",
                                                      " (in 'o2_twostation', line 108, column 15 to line 117, column 3)",
                                                      " (in 'o2_twostation', line 108, column 2 to line 117, column 3)",
                                                      " (in 'o2_twostation', line 89, column 4 to column 67)",
                                                      " (in 'o2_twostation', line 88, column 15 to line 90, column 3)",
                                                      " (in 'o2_twostation', line 88, column 2 to line 90, column 3)",
                                                      " (in 'o2_twostation', line 92, column 2 to column 42)",
                                                      " (in 'o2_twostation', line 94, column 2 to column 52)",
                                                      " (in 'o2_twostation', line 95, column 2 to column 49)",
                                                      " (in 'o2_twostation', line 96, column 2 to column 63)",
                                                      " (in 'o2_twostation', line 10, column 2 to column 20)",
                                                      " (in 'o2_twostation', line 11, column 2 to column 23)",
                                                      " (in 'o2_twostation', line 12, column 2 to column 32)",
                                                      " (in 'o2_twostation', line 13, column 2 to column 19)",
                                                      " (in 'o2_twostation', line 14, column 2 to column 22)",
                                                      " (in 'o2_twostation', line 15, column 2 to column 31)",
                                                      " (in 'o2_twostation', line 16, column 2 to column 26)",
                                                      " (in 'o2_twostation', line 17, column 2 to column 33)",
                                                      " (in 'o2_twostation', line 19, column 2 to column 40)",
                                                      " (in 'o2_twostation', line 22, column 2 to column 17)",
                                                      " (in 'o2_twostation', line 23, column 2 to column 25)",
                                                      " (in 'o2_twostation', line 24, column 2 to column 19)",
                                                      " (in 'o2_twostation', line 25, column 2 to column 17)",
                                                      " (in 'o2_twostation', line 27, column 2 to column 22)",
                                                      " (in 'o2_twostation', line 28, column 2 to column 19)",
                                                      " (in 'o2_twostation', line 29, column 2 to column 19)",
                                                      " (in 'o2_twostation', line 31, column 22 to column 23)",
                                                      " (in 'o2_twostation', line 31, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 31, column 2 to column 25)",
                                                      " (in 'o2_twostation', line 32, column 24 to column 25)",
                                                      " (in 'o2_twostation', line 32, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 32, column 2 to column 27)",
                                                      " (in 'o2_twostation', line 33, column 22 to column 23)",
                                                      " (in 'o2_twostation', line 33, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 33, column 2 to column 25)",
                                                      " (in 'o2_twostation', line 34, column 24 to column 25)",
                                                      " (in 'o2_twostation', line 34, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 34, column 2 to column 27)",
                                                      " (in 'o2_twostation', line 35, column 27 to column 28)",
                                                      " (in 'o2_twostation', line 35, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 35, column 2 to column 30)",
                                                      " (in 'o2_twostation', line 36, column 26 to column 27)",
                                                      " (in 'o2_twostation', line 36, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 36, column 2 to column 29)",
                                                      " (in 'o2_twostation', line 37, column 21 to column 22)",
                                                      " (in 'o2_twostation', line 37, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 37, column 2 to column 24)",
                                                      " (in 'o2_twostation', line 38, column 22 to column 23)",
                                                      " (in 'o2_twostation', line 38, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 38, column 2 to column 25)",
                                                      " (in 'o2_twostation', line 41, column 32 to column 33)",
                                                      " (in 'o2_twostation', line 42, column 31 to column 32)",
                                                      " (in 'o2_twostation', line 43, column 18 to column 19)",
                                                      " (in 'o2_twostation', line 51, column 21 to column 22)",
                                                      " (in 'o2_twostation', line 51, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 52, column 20 to column 21)",
                                                      " (in 'o2_twostation', line 52, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 53, column 21 to column 22)",
                                                      " (in 'o2_twostation', line 53, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 54, column 24 to column 25)",
                                                      " (in 'o2_twostation', line 54, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 99, column 24 to column 25)",
                                                      " (in 'o2_twostation', line 99, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 100, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 101, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 102, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 103, column 9 to column 10)",
                                                      " (in 'o2_twostation', line 104, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_o2_twostation final : public model_base_crtp<model_o2_twostation> {
private:
  double GPP_daily_mu;
  double GPP_daily_lower;
  double GPP_daily_sigma;
  double ER_daily_mu;
  double ER_daily_upper;
  double ER_daily_sigma;
  double K600_daily_meanlog;
  double K600_daily_sdlog;
  double err_obs_iid_sigma_scale;
  int d;
  double timestep;
  int n24;
  int n;
  double depth;
  double tt;
  int lag;
  std::vector<Eigen::Matrix<double, -1, 1>> DO_obs_up;
  std::vector<Eigen::Matrix<double, -1, 1>> DO_obs_down;
  std::vector<Eigen::Matrix<double, -1, 1>> DO_sat_up;
  std::vector<Eigen::Matrix<double, -1, 1>> DO_sat_down;
  std::vector<Eigen::Matrix<double, -1, 1>> light_mult_GPP;
  std::vector<Eigen::Matrix<double, -1, 1>> const_mult_ER;
  std::vector<Eigen::Matrix<double, -1, 1>> KO2_conv;
  std::vector<Eigen::Matrix<double, -1, 1>> lightfrac;
 
public:
  ~model_o2_twostation() { }
  
  inline std::string model_name() const final { return "model_o2_twostation"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_o2_twostation(stan::io::var_context& context__,
                      unsigned int random_seed__ = 0,
                      std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_o2_twostation_namespace::model_o2_twostation";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 44;
      context__.validate_dims("data initialization","GPP_daily_mu","double",
          context__.to_vec());
      GPP_daily_mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 44;
      GPP_daily_mu = context__.vals_r("GPP_daily_mu")[(1 - 1)];
      current_statement__ = 45;
      context__.validate_dims("data initialization","GPP_daily_lower",
          "double",context__.to_vec());
      GPP_daily_lower = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 45;
      GPP_daily_lower = context__.vals_r("GPP_daily_lower")[(1 - 1)];
      current_statement__ = 46;
      context__.validate_dims("data initialization","GPP_daily_sigma",
          "double",context__.to_vec());
      GPP_daily_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 46;
      GPP_daily_sigma = context__.vals_r("GPP_daily_sigma")[(1 - 1)];
      current_statement__ = 46;
      current_statement__ = 46;
      check_greater_or_equal(function__, "GPP_daily_sigma", GPP_daily_sigma,
                             0);
      current_statement__ = 47;
      context__.validate_dims("data initialization","ER_daily_mu","double",
          context__.to_vec());
      ER_daily_mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 47;
      ER_daily_mu = context__.vals_r("ER_daily_mu")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization","ER_daily_upper",
          "double",context__.to_vec());
      ER_daily_upper = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 48;
      ER_daily_upper = context__.vals_r("ER_daily_upper")[(1 - 1)];
      current_statement__ = 49;
      context__.validate_dims("data initialization","ER_daily_sigma",
          "double",context__.to_vec());
      ER_daily_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 49;
      ER_daily_sigma = context__.vals_r("ER_daily_sigma")[(1 - 1)];
      current_statement__ = 49;
      current_statement__ = 49;
      check_greater_or_equal(function__, "ER_daily_sigma", ER_daily_sigma, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization","K600_daily_meanlog",
          "double",context__.to_vec());
      K600_daily_meanlog = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 50;
      K600_daily_meanlog = context__.vals_r("K600_daily_meanlog")[(1 - 1)];
      current_statement__ = 51;
      context__.validate_dims("data initialization","K600_daily_sdlog",
          "double",context__.to_vec());
      K600_daily_sdlog = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 51;
      K600_daily_sdlog = context__.vals_r("K600_daily_sdlog")[(1 - 1)];
      current_statement__ = 51;
      current_statement__ = 51;
      check_greater_or_equal(function__, "K600_daily_sdlog",
                             K600_daily_sdlog, 0);
      current_statement__ = 52;
      context__.validate_dims("data initialization",
          "err_obs_iid_sigma_scale","double",context__.to_vec());
      err_obs_iid_sigma_scale = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 52;
      err_obs_iid_sigma_scale = context__.vals_r("err_obs_iid_sigma_scale")[
          (1 - 1)];
      current_statement__ = 52;
      current_statement__ = 52;
      check_greater_or_equal(function__, "err_obs_iid_sigma_scale",
                             err_obs_iid_sigma_scale, 0);
      current_statement__ = 53;
      context__.validate_dims("data initialization","d","int",
          context__.to_vec());
      d = std::numeric_limits<int>::min();
      
      current_statement__ = 53;
      d = context__.vals_i("d")[(1 - 1)];
      current_statement__ = 53;
      current_statement__ = 53;
      check_greater_or_equal(function__, "d", d, 1);
      current_statement__ = 54;
      context__.validate_dims("data initialization","timestep","double",
          context__.to_vec());
      timestep = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 54;
      timestep = context__.vals_r("timestep")[(1 - 1)];
      current_statement__ = 54;
      current_statement__ = 54;
      check_greater_or_equal(function__, "timestep", timestep, 0);
      current_statement__ = 55;
      context__.validate_dims("data initialization","n24","int",
          context__.to_vec());
      n24 = std::numeric_limits<int>::min();
      
      current_statement__ = 55;
      n24 = context__.vals_i("n24")[(1 - 1)];
      current_statement__ = 55;
      current_statement__ = 55;
      check_greater_or_equal(function__, "n24", n24, 1);
      current_statement__ = 56;
      context__.validate_dims("data initialization","n","int",
          context__.to_vec());
      n = std::numeric_limits<int>::min();
      
      current_statement__ = 56;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 56;
      current_statement__ = 56;
      check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 57;
      context__.validate_dims("data initialization","depth","double",
          context__.to_vec());
      depth = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 57;
      depth = context__.vals_r("depth")[(1 - 1)];
      current_statement__ = 57;
      current_statement__ = 57;
      check_greater_or_equal(function__, "depth", depth, 0);
      current_statement__ = 58;
      context__.validate_dims("data initialization","tt","double",
          context__.to_vec());
      tt = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 58;
      tt = context__.vals_r("tt")[(1 - 1)];
      current_statement__ = 58;
      current_statement__ = 58;
      check_greater_or_equal(function__, "tt", tt, 0);
      current_statement__ = 59;
      context__.validate_dims("data initialization","lag","int",
          context__.to_vec());
      lag = std::numeric_limits<int>::min();
      
      current_statement__ = 59;
      lag = context__.vals_i("lag")[(1 - 1)];
      current_statement__ = 59;
      current_statement__ = 59;
      check_greater_or_equal(function__, "lag", lag, 0);
      current_statement__ = 60;
      validate_non_negative_index("DO_obs_up", "n", n);
      current_statement__ = 61;
      validate_non_negative_index("DO_obs_up", "d", d);
      current_statement__ = 62;
      context__.validate_dims("data initialization","DO_obs_up","double",
          context__.to_vec(n, d));
      DO_obs_up = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(DO_obs_up, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> DO_obs_up_flat__;
        current_statement__ = 62;
        assign(DO_obs_up_flat__, nil_index_list(),
          context__.vals_r("DO_obs_up"),
          "assigning variable DO_obs_up_flat__");
        current_statement__ = 62;
        pos__ = 1;
        current_statement__ = 62;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 62;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 62;
            assign(DO_obs_up,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              DO_obs_up_flat__[(pos__ - 1)], "assigning variable DO_obs_up");
            current_statement__ = 62;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 63;
      validate_non_negative_index("DO_obs_down", "n", n);
      current_statement__ = 64;
      validate_non_negative_index("DO_obs_down", "d", d);
      current_statement__ = 65;
      context__.validate_dims("data initialization","DO_obs_down","double",
          context__.to_vec(n, d));
      DO_obs_down = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(DO_obs_down, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> DO_obs_down_flat__;
        current_statement__ = 65;
        assign(DO_obs_down_flat__, nil_index_list(),
          context__.vals_r("DO_obs_down"),
          "assigning variable DO_obs_down_flat__");
        current_statement__ = 65;
        pos__ = 1;
        current_statement__ = 65;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 65;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 65;
            assign(DO_obs_down,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              DO_obs_down_flat__[(pos__ - 1)],
              "assigning variable DO_obs_down");
            current_statement__ = 65;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 66;
      validate_non_negative_index("DO_sat_up", "n", n);
      current_statement__ = 67;
      validate_non_negative_index("DO_sat_up", "d", d);
      current_statement__ = 68;
      context__.validate_dims("data initialization","DO_sat_up","double",
          context__.to_vec(n, d));
      DO_sat_up = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(DO_sat_up, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> DO_sat_up_flat__;
        current_statement__ = 68;
        assign(DO_sat_up_flat__, nil_index_list(),
          context__.vals_r("DO_sat_up"),
          "assigning variable DO_sat_up_flat__");
        current_statement__ = 68;
        pos__ = 1;
        current_statement__ = 68;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 68;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 68;
            assign(DO_sat_up,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              DO_sat_up_flat__[(pos__ - 1)], "assigning variable DO_sat_up");
            current_statement__ = 68;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 69;
      validate_non_negative_index("DO_sat_down", "n", n);
      current_statement__ = 70;
      validate_non_negative_index("DO_sat_down", "d", d);
      current_statement__ = 71;
      context__.validate_dims("data initialization","DO_sat_down","double",
          context__.to_vec(n, d));
      DO_sat_down = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(DO_sat_down, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> DO_sat_down_flat__;
        current_statement__ = 71;
        assign(DO_sat_down_flat__, nil_index_list(),
          context__.vals_r("DO_sat_down"),
          "assigning variable DO_sat_down_flat__");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 71;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 71;
            assign(DO_sat_down,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              DO_sat_down_flat__[(pos__ - 1)],
              "assigning variable DO_sat_down");
            current_statement__ = 71;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 72;
      validate_non_negative_index("light_mult_GPP", "n", n);
      current_statement__ = 73;
      validate_non_negative_index("light_mult_GPP", "d", d);
      current_statement__ = 74;
      context__.validate_dims("data initialization","light_mult_GPP",
          "double",context__.to_vec(n, d));
      light_mult_GPP = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(light_mult_GPP, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> light_mult_GPP_flat__;
        current_statement__ = 74;
        assign(light_mult_GPP_flat__, nil_index_list(),
          context__.vals_r("light_mult_GPP"),
          "assigning variable light_mult_GPP_flat__");
        current_statement__ = 74;
        pos__ = 1;
        current_statement__ = 74;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 74;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 74;
            assign(light_mult_GPP,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              light_mult_GPP_flat__[(pos__ - 1)],
              "assigning variable light_mult_GPP");
            current_statement__ = 74;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 75;
      validate_non_negative_index("const_mult_ER", "n", n);
      current_statement__ = 76;
      validate_non_negative_index("const_mult_ER", "d", d);
      current_statement__ = 77;
      context__.validate_dims("data initialization","const_mult_ER","double",
          context__.to_vec(n, d));
      const_mult_ER = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(const_mult_ER, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> const_mult_ER_flat__;
        current_statement__ = 77;
        assign(const_mult_ER_flat__, nil_index_list(),
          context__.vals_r("const_mult_ER"),
          "assigning variable const_mult_ER_flat__");
        current_statement__ = 77;
        pos__ = 1;
        current_statement__ = 77;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 77;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 77;
            assign(const_mult_ER,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              const_mult_ER_flat__[(pos__ - 1)],
              "assigning variable const_mult_ER");
            current_statement__ = 77;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 78;
      validate_non_negative_index("KO2_conv", "n", n);
      current_statement__ = 79;
      validate_non_negative_index("KO2_conv", "d", d);
      current_statement__ = 80;
      context__.validate_dims("data initialization","KO2_conv","double",
          context__.to_vec(n, d));
      KO2_conv = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(KO2_conv, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> KO2_conv_flat__;
        current_statement__ = 80;
        assign(KO2_conv_flat__, nil_index_list(),
          context__.vals_r("KO2_conv"), "assigning variable KO2_conv_flat__");
        current_statement__ = 80;
        pos__ = 1;
        current_statement__ = 80;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 80;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 80;
            assign(KO2_conv,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              KO2_conv_flat__[(pos__ - 1)], "assigning variable KO2_conv");
            current_statement__ = 80;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 81;
      validate_non_negative_index("lightfrac", "n", n);
      current_statement__ = 82;
      validate_non_negative_index("lightfrac", "d", d);
      current_statement__ = 83;
      context__.validate_dims("data initialization","lightfrac","double",
          context__.to_vec(n, d));
      lightfrac = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(lightfrac, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> lightfrac_flat__;
        current_statement__ = 83;
        assign(lightfrac_flat__, nil_index_list(),
          context__.vals_r("lightfrac"),
          "assigning variable lightfrac_flat__");
        current_statement__ = 83;
        pos__ = 1;
        current_statement__ = 83;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 83;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 83;
            assign(lightfrac,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              lightfrac_flat__[(pos__ - 1)], "assigning variable lightfrac");
            current_statement__ = 83;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 84;
      validate_non_negative_index("GPP_daily", "d", d);
      current_statement__ = 85;
      validate_non_negative_index("ER_daily", "d", d);
      current_statement__ = 86;
      validate_non_negative_index("K600_daily", "d", d);
      current_statement__ = 87;
      validate_non_negative_index("GPP_inst", "n", n);
      current_statement__ = 88;
      validate_non_negative_index("GPP_inst", "d", d);
      current_statement__ = 89;
      validate_non_negative_index("ER_inst", "n", n);
      current_statement__ = 90;
      validate_non_negative_index("ER_inst", "d", d);
      current_statement__ = 91;
      validate_non_negative_index("KO2_inst", "n", n);
      current_statement__ = 92;
      validate_non_negative_index("KO2_inst", "d", d);
      current_statement__ = 93;
      validate_non_negative_index("DO_mod_down", "n", n);
      current_statement__ = 94;
      validate_non_negative_index("DO_mod_down", "d", d);
      current_statement__ = 95;
      validate_non_negative_index("err_obs_iid", "n", n);
      current_statement__ = 96;
      validate_non_negative_index("err_obs_iid", "d", d);
      current_statement__ = 97;
      validate_non_negative_index("GPP", "d", d);
      current_statement__ = 98;
      validate_non_negative_index("ER", "d", d);
      current_statement__ = 99;
      validate_non_negative_index("DO_obs_down_vec", "n", n);
      current_statement__ = 100;
      validate_non_negative_index("DO_mod_down_vec", "n", n);
      current_statement__ = 101;
      validate_non_negative_index("DO_R2", "d", d);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += d;
      num_params_r__ += d;
      num_params_r__ += d;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_o2_twostation_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> GPP_daily;
      GPP_daily = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(GPP_daily, DUMMY_VAR__);
      
      current_statement__ = 1;
      GPP_daily = in__.vector(d);
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 1;
        if (jacobian__) {
          current_statement__ = 1;
          assign(GPP_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(GPP_daily[(sym1__ - 1)],
              GPP_daily_lower, lp__), "assigning variable GPP_daily");
        } else {
          current_statement__ = 1;
          assign(GPP_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(GPP_daily[(sym1__ - 1)], GPP_daily_lower),
            "assigning variable GPP_daily");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> ER_daily;
      ER_daily = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(ER_daily, DUMMY_VAR__);
      
      current_statement__ = 2;
      ER_daily = in__.vector(d);
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(ER_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::ub_constrain(ER_daily[(sym1__ - 1)], ER_daily_upper,
              lp__), "assigning variable ER_daily");
        } else {
          current_statement__ = 2;
          assign(ER_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::ub_constrain(ER_daily[(sym1__ - 1)], ER_daily_upper),
            "assigning variable ER_daily");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> K600_daily;
      K600_daily = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(K600_daily, DUMMY_VAR__);
      
      current_statement__ = 3;
      K600_daily = in__.vector(d);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 3;
        if (jacobian__) {
          current_statement__ = 3;
          assign(K600_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(K600_daily[(sym1__ - 1)], 0, lp__),
            "assigning variable K600_daily");
        } else {
          current_statement__ = 3;
          assign(K600_daily, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(K600_daily[(sym1__ - 1)], 0),
            "assigning variable K600_daily");
        }}
      local_scalar_t__ err_obs_iid_sigma_scaled;
      err_obs_iid_sigma_scaled = DUMMY_VAR__;
      
      current_statement__ = 4;
      err_obs_iid_sigma_scaled = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        err_obs_iid_sigma_scaled = stan::math::lb_constrain(
                                     err_obs_iid_sigma_scaled, 0, lp__);
      } else {
        current_statement__ = 4;
        err_obs_iid_sigma_scaled = stan::math::lb_constrain(
                                     err_obs_iid_sigma_scaled, 0);
      }
      local_scalar_t__ err_obs_iid_sigma;
      err_obs_iid_sigma = DUMMY_VAR__;
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> GPP_inst;
      GPP_inst = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(n, Eigen::Matrix<local_scalar_t__, -1, 1>(d));
      stan::math::fill(GPP_inst, DUMMY_VAR__);
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> ER_inst;
      ER_inst = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(n, Eigen::Matrix<local_scalar_t__, -1, 1>(d));
      stan::math::fill(ER_inst, DUMMY_VAR__);
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> KO2_inst;
      KO2_inst = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(n, Eigen::Matrix<local_scalar_t__, -1, 1>(d));
      stan::math::fill(KO2_inst, DUMMY_VAR__);
      
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> DO_mod_down;
      DO_mod_down = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(n, Eigen::Matrix<local_scalar_t__, -1, 1>(d));
      stan::math::fill(DO_mod_down, DUMMY_VAR__);
      
      current_statement__ = 10;
      err_obs_iid_sigma = (err_obs_iid_sigma_scale *
                            err_obs_iid_sigma_scaled);
      current_statement__ = 15;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 11;
        assign(GPP_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(GPP_daily, light_mult_GPP[(i - 1)]),
          "assigning variable GPP_inst");
        current_statement__ = 12;
        assign(ER_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(ER_daily, const_mult_ER[(i - 1)]),
          "assigning variable ER_inst");
        current_statement__ = 13;
        assign(KO2_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(K600_daily, KO2_conv[(i - 1)]),
          "assigning variable KO2_inst");}
      current_statement__ = 18;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 16;
        assign(DO_mod_down,
          cons_list(index_uni((i + lag)), nil_index_list()),
          elt_divide(
            add(
              add(
                add(DO_obs_up[(i - 1)],
                  elt_multiply(divide(GPP_inst[(i - 1)], depth),
                    lightfrac[(i - 1)])),
                multiply(divide(ER_inst[(i - 1)], depth), tt)),
              divide(
                elt_multiply(multiply(KO2_conv[(i - 1)], tt),
                  add(subtract(DO_sat_up[(i - 1)], DO_obs_up[(i - 1)]),
                    DO_sat_down[((i + lag) - 1)])), 2)),
            add(1, divide(multiply(KO2_conv[(i - 1)], tt), 2))),
          "assigning variable DO_mod_down");}
      current_statement__ = 5;
      current_statement__ = 5;
      check_greater_or_equal(function__, "err_obs_iid_sigma",
                             err_obs_iid_sigma, 0);
      {
        current_statement__ = 39;
        for (int i = 1; i <= n; ++i) {
          current_statement__ = 37;
          lp_accum__.add(
            normal_lpdf<propto__>(DO_obs_down[(i - 1)],
              DO_mod_down[((i + lag) - 1)], err_obs_iid_sigma));}
        current_statement__ = 40;
        lp_accum__.add(cauchy_lpdf<propto__>(err_obs_iid_sigma_scaled, 0, 1));
        current_statement__ = 41;
        lp_accum__.add(
          normal_lpdf<propto__>(GPP_daily, GPP_daily_mu, GPP_daily_sigma));
        current_statement__ = 42;
        lp_accum__.add(
          normal_lpdf<propto__>(ER_daily, ER_daily_mu, ER_daily_sigma));
        current_statement__ = 43;
        lp_accum__.add(
          lognormal_lpdf<propto__>(K600_daily, K600_daily_meanlog,
            K600_daily_sdlog));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_o2_twostation_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> GPP_daily;
      GPP_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(GPP_daily, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      GPP_daily = in__.vector(d);
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 1;
        assign(GPP_daily, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(GPP_daily[(sym1__ - 1)], GPP_daily_lower),
          "assigning variable GPP_daily");}
      Eigen::Matrix<double, -1, 1> ER_daily;
      ER_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(ER_daily, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      ER_daily = in__.vector(d);
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 2;
        assign(ER_daily, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::ub_constrain(ER_daily[(sym1__ - 1)], ER_daily_upper),
          "assigning variable ER_daily");}
      Eigen::Matrix<double, -1, 1> K600_daily;
      K600_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(K600_daily, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      K600_daily = in__.vector(d);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 3;
        assign(K600_daily, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(K600_daily[(sym1__ - 1)], 0),
          "assigning variable K600_daily");}
      double err_obs_iid_sigma_scaled;
      err_obs_iid_sigma_scaled = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      err_obs_iid_sigma_scaled = in__.scalar();
      current_statement__ = 4;
      err_obs_iid_sigma_scaled = stan::math::lb_constrain(
                                   err_obs_iid_sigma_scaled, 0);
      double err_obs_iid_sigma;
      err_obs_iid_sigma = std::numeric_limits<double>::quiet_NaN();
      
      std::vector<Eigen::Matrix<double, -1, 1>> GPP_inst;
      GPP_inst = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(GPP_inst, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<Eigen::Matrix<double, -1, 1>> ER_inst;
      ER_inst = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(ER_inst, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<Eigen::Matrix<double, -1, 1>> KO2_inst;
      KO2_inst = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(KO2_inst, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<Eigen::Matrix<double, -1, 1>> DO_mod_down;
      DO_mod_down = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(DO_mod_down, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(GPP_daily[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(ER_daily[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(K600_daily[(sym1__ - 1)]);}
      vars__.emplace_back(err_obs_iid_sigma_scaled);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 10;
      err_obs_iid_sigma = (err_obs_iid_sigma_scale *
                            err_obs_iid_sigma_scaled);
      current_statement__ = 15;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 11;
        assign(GPP_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(GPP_daily, light_mult_GPP[(i - 1)]),
          "assigning variable GPP_inst");
        current_statement__ = 12;
        assign(ER_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(ER_daily, const_mult_ER[(i - 1)]),
          "assigning variable ER_inst");
        current_statement__ = 13;
        assign(KO2_inst, cons_list(index_uni(i), nil_index_list()),
          elt_multiply(K600_daily, KO2_conv[(i - 1)]),
          "assigning variable KO2_inst");}
      current_statement__ = 18;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 16;
        assign(DO_mod_down,
          cons_list(index_uni((i + lag)), nil_index_list()),
          elt_divide(
            add(
              add(
                add(DO_obs_up[(i - 1)],
                  elt_multiply(divide(GPP_inst[(i - 1)], depth),
                    lightfrac[(i - 1)])),
                multiply(divide(ER_inst[(i - 1)], depth), tt)),
              divide(
                elt_multiply(multiply(KO2_conv[(i - 1)], tt),
                  add(subtract(DO_sat_up[(i - 1)], DO_obs_up[(i - 1)]),
                    DO_sat_down[((i + lag) - 1)])), 2)),
            add(1, divide(multiply(KO2_conv[(i - 1)], tt), 2))),
          "assigning variable DO_mod_down");}
      current_statement__ = 5;
      current_statement__ = 5;
      check_greater_or_equal(function__, "err_obs_iid_sigma",
                             err_obs_iid_sigma, 0);
      if (emit_transformed_parameters__) {
        vars__.emplace_back(err_obs_iid_sigma);
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            vars__.emplace_back(GPP_inst[(sym2__ - 1)][(sym1__ - 1)]);}}
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            vars__.emplace_back(ER_inst[(sym2__ - 1)][(sym1__ - 1)]);}}
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            vars__.emplace_back(KO2_inst[(sym2__ - 1)][(sym1__ - 1)]);}}
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            vars__.emplace_back(DO_mod_down[(sym2__ - 1)][(sym1__ - 1)]);}}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<Eigen::Matrix<double, -1, 1>> err_obs_iid;
      err_obs_iid = std::vector<Eigen::Matrix<double, -1, 1>>(n, Eigen::Matrix<double, -1, 1>(d));
      stan::math::fill(err_obs_iid, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> GPP;
      GPP = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(GPP, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> ER;
      ER = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(ER, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> DO_obs_down_vec;
      DO_obs_down_vec = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(DO_obs_down_vec, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> DO_mod_down_vec;
      DO_mod_down_vec = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(DO_mod_down_vec, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> DO_R2;
      DO_R2 = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(DO_R2, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 27;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 25;
        assign(err_obs_iid, cons_list(index_uni(i), nil_index_list()),
          subtract(DO_mod_down[(i - 1)], DO_obs_down[(i - 1)]),
          "assigning variable err_obs_iid");}
      current_statement__ = 36;
      for (int j = 1; j <= d; ++j) {
        current_statement__ = 28;
        assign(GPP, cons_list(index_uni(j), nil_index_list()),
          (sum(
             rvalue(GPP_inst,
               cons_list(index_min_max(1, n24),
                 cons_list(index_uni(j), nil_index_list())), "GPP_inst")) /
            n24), "assigning variable GPP");
        current_statement__ = 29;
        assign(ER, cons_list(index_uni(j), nil_index_list()),
          (sum(
             rvalue(ER_inst,
               cons_list(index_min_max(1, n24),
                 cons_list(index_uni(j), nil_index_list())), "ER_inst")) /
            n24), "assigning variable ER");
        current_statement__ = 33;
        for (int i = 1; i <= n; ++i) {
          current_statement__ = 30;
          assign(DO_mod_down_vec, cons_list(index_uni(i), nil_index_list()),
            DO_mod_down[(i - 1)][(j - 1)],
            "assigning variable DO_mod_down_vec");
          current_statement__ = 31;
          assign(DO_obs_down_vec, cons_list(index_uni(i), nil_index_list()),
            DO_obs_down[(i - 1)][(j - 1)],
            "assigning variable DO_obs_down_vec");}
        current_statement__ = 34;
        assign(DO_R2, cons_list(index_uni(j), nil_index_list()),
          (1 -
            (sum(
               elt_multiply(subtract(DO_mod_down_vec, DO_obs_down_vec),
                 subtract(DO_mod_down_vec, DO_obs_down_vec))) /
              sum(
                elt_multiply(
                  subtract(DO_obs_down_vec, mean(DO_obs_down_vec)),
                  subtract(DO_obs_down_vec, mean(DO_obs_down_vec)))))),
          "assigning variable DO_R2");}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          vars__.emplace_back(err_obs_iid[(sym2__ - 1)][(sym1__ - 1)]);}}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(GPP[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(ER[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        vars__.emplace_back(DO_obs_down_vec[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        vars__.emplace_back(DO_mod_down_vec[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(DO_R2[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> GPP_daily;
      GPP_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(GPP_daily, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> GPP_daily_flat__;
        current_statement__ = 1;
        assign(GPP_daily_flat__, nil_index_list(),
          context__.vals_r("GPP_daily"),
          "assigning variable GPP_daily_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 1;
          assign(GPP_daily, cons_list(index_uni(sym1__), nil_index_list()),
            GPP_daily_flat__[(pos__ - 1)], "assigning variable GPP_daily");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> GPP_daily_free__;
      GPP_daily_free__ = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(GPP_daily_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 1;
        assign(GPP_daily_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(GPP_daily[(sym1__ - 1)], GPP_daily_lower),
          "assigning variable GPP_daily_free__");}
      Eigen::Matrix<double, -1, 1> ER_daily;
      ER_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(ER_daily, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> ER_daily_flat__;
        current_statement__ = 2;
        assign(ER_daily_flat__, nil_index_list(),
          context__.vals_r("ER_daily"), "assigning variable ER_daily_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 2;
          assign(ER_daily, cons_list(index_uni(sym1__), nil_index_list()),
            ER_daily_flat__[(pos__ - 1)], "assigning variable ER_daily");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> ER_daily_free__;
      ER_daily_free__ = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(ER_daily_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 2;
        assign(ER_daily_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::ub_free(ER_daily[(sym1__ - 1)], ER_daily_upper),
          "assigning variable ER_daily_free__");}
      Eigen::Matrix<double, -1, 1> K600_daily;
      K600_daily = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(K600_daily, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> K600_daily_flat__;
        current_statement__ = 3;
        assign(K600_daily_flat__, nil_index_list(),
          context__.vals_r("K600_daily"),
          "assigning variable K600_daily_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 3;
          assign(K600_daily, cons_list(index_uni(sym1__), nil_index_list()),
            K600_daily_flat__[(pos__ - 1)], "assigning variable K600_daily");
          current_statement__ = 3;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> K600_daily_free__;
      K600_daily_free__ = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(K600_daily_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        current_statement__ = 3;
        assign(K600_daily_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(K600_daily[(sym1__ - 1)], 0),
          "assigning variable K600_daily_free__");}
      double err_obs_iid_sigma_scaled;
      err_obs_iid_sigma_scaled = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      err_obs_iid_sigma_scaled = context__.vals_r("err_obs_iid_sigma_scaled")[
          (1 - 1)];
      double err_obs_iid_sigma_scaled_free__;
      err_obs_iid_sigma_scaled_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      err_obs_iid_sigma_scaled_free__ = stan::math::lb_free(
                                          err_obs_iid_sigma_scaled, 0);
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(GPP_daily_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(ER_daily_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        vars__.emplace_back(K600_daily_free__[(sym1__ - 1)]);}
      vars__.emplace_back(err_obs_iid_sigma_scaled_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("GPP_daily");
    names__.emplace_back("ER_daily");
    names__.emplace_back("K600_daily");
    names__.emplace_back("err_obs_iid_sigma_scaled");
    names__.emplace_back("err_obs_iid_sigma");
    names__.emplace_back("GPP_inst");
    names__.emplace_back("ER_inst");
    names__.emplace_back("KO2_inst");
    names__.emplace_back("DO_mod_down");
    names__.emplace_back("err_obs_iid");
    names__.emplace_back("GPP");
    names__.emplace_back("ER");
    names__.emplace_back("DO_obs_down_vec");
    names__.emplace_back("DO_mod_down_vec");
    names__.emplace_back("DO_R2");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n),
                                             static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n),
                                             static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n),
                                             static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n),
                                             static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n),
                                             static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(d)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "GPP_daily" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ER_daily" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "K600_daily" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "err_obs_iid_sigma_scaled");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "err_obs_iid_sigma");
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "GPP_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ER_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "KO2_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "DO_mod_down" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "err_obs_iid" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "GPP" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ER" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_obs_down_vec" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_mod_down_vec" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_R2" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "GPP_daily" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ER_daily" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "K600_daily" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "err_obs_iid_sigma_scaled");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "err_obs_iid_sigma");
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "GPP_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ER_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "KO2_inst" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "DO_mod_down" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "err_obs_iid" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "GPP" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ER" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_obs_down_vec" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_mod_down_vec" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DO_R2" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"GPP_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"ER_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"K600_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"err_obs_iid_sigma_scaled\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"err_obs_iid_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"GPP_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"ER_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"KO2_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"DO_mod_down\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"err_obs_iid\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"generated_quantities\"},{\"name\":\"GPP\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"},{\"name\":\"ER\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_obs_down_vec\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_mod_down_vec\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_R2\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"GPP_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"ER_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"K600_daily\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"parameters\"},{\"name\":\"err_obs_iid_sigma_scaled\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"err_obs_iid_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"GPP_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"ER_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"KO2_inst\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"DO_mod_down\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"transformed_parameters\"},{\"name\":\"err_obs_iid\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"vector\",\"length\":" << d << "}},\"block\":\"generated_quantities\"},{\"name\":\"GPP\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"},{\"name\":\"ER\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_obs_down_vec\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_mod_down_vec\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"},{\"name\":\"DO_R2\",\"type\":{\"name\":\"vector\",\"length\":" << d << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_o2_twostation_namespace::model_o2_twostation;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_o2_twostation_namespace::profiles__;
}
#endif
#endif
